version: '3.0'
services:
 # nginxconfiguration
  web:
    image: nginx:1.17
    container_name: webserver
    depends_on:
      - php
    volumes:
      - ./content:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
 # php-fpm configuration
  php:
    build:
      ./php
    container_name: php7
    volumes:
      - ./content:/var/www/html
    depends_on:
      - db
 # mysql configuration
  db:
    image: mysql:8.0
    container_name: mysql80
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./content/sql/bloodbank.sql:/docker-entrypoint-initdb.d/bloodbank.sql
    environment:
      MYSQL_DATABASE: "bloodbank"
      MYSQL_USER: "bbms"
      MYSQL_PASSWORD: "QeyUDkK7k"
      MYSQL_ROOT_PASSWORD: QeyUDky5690kGFTG"
